### ISSUE TITLE
Statements containing "None" Agent

### ISSUE THREAD

**Issue by guerrerosimonl** [sorgerlab/indra#1028]
Hi !

Using REACH to read the articles text extracted with the indra.literature module gives a problem for some specific pmids. An example is pmid:18724895. Processing this article with REACH gives two statements: 
[Activation(DNA damage(), None), Activation(DNA damage(), None)]
And when trying to do the preassembly with those statements with the command assemble_corpus.run_preassembly(), it gives an error "AttributeError: 'NoneType' object has no attribute 'matches_key'". 

When we are running many pmids in the same time is annoying because we need to find and discard the statements manually. 

Is there a way to avoid this kind of statements?

Thank you in advance!

Laura

**Comment by bgyori** [comment]
Hi, generally the object of an Activation statement is not expected to be `None`. I looked into this and found that it is due to a change in the REACH output format that INDRA has not yet been adapted to (namely, when an amount regulation is embedded in an activation event). We will make a change to `indra.sources.reach` to improve the handling of these cases, which will eliminate the `None` entry in this and similar cases. 

Otherwise, you can easily filter out such statements before the fix is applied by doing e.g., 
```
from indra.statements import RegulateAmount, RegulateActivity
stmts_filtered = [s for s in stmts if (isinstance(s, (RegulateAmount, RegulateActivity)) and s.obj is not None)]
```
