### ISSUE TITLE
Differential annotation for agents with the same acronym

### ISSUE THREAD

**Issue by guerrerosimonl** [sorgerlab/indra#1059]
Hi!

I found a problem for acronyms that can be identified as different agents. For example:

For pmid 30383265, when creating INDRA statements with REACH, the agent DDT is identified as both the chemical compound (PubChem ID 3036) and the protein (Uniprot P30046). But in this paper they are only referring to the chemical compound. Thus, the network is giving extra edges for a couple of relationships. 

Is there any way to solve this?

Thank you in advance!!

Laura

**Comment by bgyori** [comment]
The original issue with grounding happens in REACH, so if you find that it is something to be fixed in the reading system, you could post it on their Github repo as an issue. INDRA's GroundingMapper gives you a way to apply custom mappings for entity texts that you want to remap. INDRA's built-in default grounding map file is at https://github.com/sorgerlab/indra/blob/master/indra/resources/famplex/grounding_map.csv. You can make a copy of this file and extend it or you can start a new file with the same format to add your custom mappings. In your case, you could add a line with DDT and its PUBCHEM ID following examples of other mappings in the file.

You can then load these custom mappings and pass it to the map_grounding function to apply them. 
```python
from indra.tools import assemble_corpus as ac
from indra.preassembler.grounding.mapper import load_grounding_map
gm = load_grounding_map('path/to/grounding_map.csv')
stmts = ac.map_grounding(stmts, grounding_map=gm)
```

**Comment by bgyori** [comment]
I assume the grounding mapping solution above works, if not, please reopen the issue.

**Comment by guerrerosimonl** [comment]
Sorry I forgot to answer! Yes, it was solved. Thanks a lot!

Laura
