### ISSUE TITLE
Display Clickthrough API warning only when actually used

### ISSUE THREAD

**Issue by bgyori** [sorgerlab/indra#106]
When importing indra.literature, a Clickthrough API warning is displayed. It would be good to move this down somewhere more specific so that it is only displayed when it's relevant:

```
CrossRef Clickthrough API key could not be found.
[...]/indra/indra/literature/cr_clickthrough_key
```

**Comment by johnbachman** [comment]
Thinking about this issue it strikes me that we might want to unify our approach to these kinds of keys--for example, to have a common procedure for looking up keys in files and then environment variables, and then giving standardized messages as appropriate. Perhaps some kind of load_key() function in indra.util.

We might also consider that when using keys from files, they should be looked up in a single directory, let's say a default dir of indra/keys.

So the procedure could be as follows:
- look for key file in indra/keys.
- if not found there, look for INDRA_API_KEYS environment variable to find the directory in a different place, and look for keys there.
- if the INDRA_API_KEYS environment variable doesn't exist, or if the key is not found in that directory, then we look for an appropriately named environment variable.

The S3 credentials might be a little funky to handle this way, since boto already has its own procedure to look for these credentials, so maybe this would be limited to the various API keys (Elsevier, crossref, Biogrid, etc.).
