### ISSUE TITLE
compiling statements into a collection from multiple documents

### ISSUE THREAD

**Issue by kingfish777** [sorgerlab/indra#1117]
Greetings:
Reading the documentation, there seems to be a gap in how to go from statements deriving from reading one document using a reader (say REACH) and compiling multiple documents into a collection or library. What are some best practices that you can recommend using the indra API. 
Thanks!
Scott

**Comment by bgyori** [comment]
Hi @kingfish777, lists of "raw" INDRA Statements obtained from any of the `indra.sources` modules can by simply be concatenated into a list to collect Statements from multiple documents or input sources. For example, assuming you have a list of PMIDs, you can do something like

```python
from indra.sources import reach
stmts = []
for pmid in pmids:
    rp = reach.process_pubmed_abstract(pmid)
    stmts += rp.statements
```
to collect a list of "raw" statements from multiple documents.

INDRA then provides a multitude of modules that operate over lists of INDRA Statements and implement various "knowledge assembly" functionalities. These are introduced in this section of the README: https://github.com/sorgerlab/indra#internal-knowledge-assembly with two examples of typical assembly workflows that you can start with.

**Comment by kingfish777** [comment]
Many thanks!

**Comment by kingfish777** [comment]
Two more questions, if that is ok: 
* what would be the best way to persist statements and associated metadata (including provenance in terms of source article and sentence) into local storage?
* building the assembler, why would stmts = ac.map_grounding(stmts) strip out all of the statements to the empty []. In other words, how does one set the grounding?

**Comment by bgyori** [comment]
In terms of persistence: we usual save INDRA Statements either in Python pickle files (https://docs.python.org/3/library/pickle.html) which is convenient because it serializes and deserializes the Python objects directly, or we use JSON serialization.

For pickling, you can try e.g., 
```python
import pickle
with open('statements.pkl', 'wb') as fh:
    pickle.dump(stmt, fh)
```
For JSON serialization, you can do
```python
from indra.statements import stmts_to_json_file
stmts_to_json_file(stmts, 'statements.json')
```
INDRA Statements carry metadata about source text references (PMID, etc.) as well as evidence sentences in their `evidence` attribute so these are saved along with each Statement.

As for the grounding mapping, it shouldn't normally remove all statements. The typical behavior is to modify Agent groundings where appropriate according to a built-in or user-supplied mapping, and filter out a (usually) small set of statements that have Agents that should be ignored according to a built-in or user-supplied list. You'd have to provide a bit more detail for what you pass to ac.map_grounding to help figure out what the issue could be.

**Comment by bgyori** [comment]
I'll close this for now, if you have other questions, please follow up.
