### ISSUE TITLE
Unicode issue in reading pipeline in  Python 2

### ISSUE THREAD

**Issue by johnbachman** [sorgerlab/indra#120]
```
Traceback (most recent call last):
  File "/pmc/indra/indra/tools/reading/run_reach_on_pmids.py", line 296, in <module>
    source_text)
  File "/pmc/indra/indra/literature/s3_client.py", line 248, in put_reach_output
    full_json_gz = gzip_string(json.dumps(reach_output), 'reach_output.json')
  File "/pmc/indra/indra/literature/s3_client.py", line 258, in gzip_string
    gzf = gzip.GzipFile(name, 'wb', 6, buf)
  File "/usr/lib/python2.7/gzip.py", line 133, in __init__
    self._write_gzip_header()
  File "/usr/lib/python2.7/gzip.py", line 178, in _write_gzip_header
    self.fileobj.write(fname + '\000')
TypeError: 'unicode' does not have the buffer interface
```

**Comment by jmuhlich** [comment]
Your dirt-old Python on that AMI (2.7.4 Ben tells me) has a bug in the gzip module that fails to properly handle unicode filenames, even if they are all-ascii. In a later version, some code was added to check if the filename is a unicode object and encode it -- in latin-1 according to the gzip spec by the way, not utf8! So this really suggests we should build our own up-to-date Python on EC2.

**Comment by jmuhlich** [comment]
Actually this is a bit weirder. Passing a unicode object that's ascii-safe as the filename to gzip.GzipFile works just fine (but it does choke if you pass something that has non-ascii in it, which is not your situation). Your bug occurs because you pass an io.BytesIO as the fileobj of the GzipFile, and BytesIO.write() will only accept str not unicode even if the unicode is ascii-safe. The Python 2.7.9+ fix for unicode filenames in GzipFile will still fix this problem, however, as it will always ensure the filename written to the gzip file header is a str not a unicode.

**Comment by jmuhlich** [comment]
From my reading of the gzip.py source, this would happen if fname is a 
unicode and not a str at line 178. But given the preceding code, I can't 
see how that can actually happen. Can you show me what machine that was 
running on so I can inspect some things?

**Comment by johnbachman** [comment]
It happened on the EC2 AMI ami-e62964f1, I believe.

**Comment by bgyori** [comment]
This is not really relevant anymore so I'm closing it.
