### ISSUE TITLE
Obtaining INDRA statements about the reactome coagulation cascade

### ISSUE THREAD

**Issue by djinnome** [sorgerlab/indra#1235]
Hi folks,

I would love to assemble a set of INDRA statements that captures the  [reactome coagulation cascade](https://reactome.org/content/detail/R-HSA-140875) 

[reactome.coagulation-cascade.biopax.zip](https://github.com/sorgerlab/indra/files/5974164/reactome.coagulation-cascade.biopax.zip)

Attached is a biopax file I downloaded from reactome that contains `FragmentFeatures` that  pybiopax correctly parses, but the biopax processor does not currently  process:

[`# TODO: handle BindingFeatures and FragmentFeatures here`](https://github.com/sorgerlab/indra/blob/master/indra/sources/biopax/processor.py#L130)

Is there a workaround that can get me what I am hoping for?

Sincerely,

Jeremy

**Comment by bgyori** [comment]
Thanks @djinnome, I can look into this. I developed the BioPAX processor against Pathway Commons, and BioPAX content sourced from other databases often has a different enough flavor that things aren't picked up. I wonder to what extent mechanisms in this pathway would be recapitulated from the PathwayCommons import of Reactome. In any case, let me check and comment on what we'd have to change to make this work.

**Comment by djinnome** [comment]
Hi @bgyori Thanks for looking into this. For a bit more (biological) context,  the coagulation cascade is a series of events where different proteins cleave one another until a protein fragment named fibrin is created that polymerizes into a clot.
![Fibrin](https://s3-us-west-2.amazonaws.com/courses-images/wp-content/uploads/sites/1940/2017/05/29213757/blood-coagulation-pathway.png)

The  pathway commons equivalents are these:
* [Extrinsic coagulation pathway](https://apps.pathwaycommons.org/pathways?uri=http%3A%2F%2Fidentifiers.org%2Freactome%2FR-HSA-140834)
* [Intrinsic coagulation pathway](https://apps.pathwaycommons.org/pathways?uri=http%3A%2F%2Fidentifiers.org%2Freactome%2FR-HSA-140837)
* [Common coagulation pathway](https://apps.pathwaycommons.org/pathways?uri=http%3A%2F%2Fidentifiers.org%2Freactome%2FR-HSA-140875)

Pathway-commons does [normalize and clean the biopax that it gets from Reactome.](http://www.pathwaycommons.org/archives/PC2/v12/original-intermediate-data/reactome/)

So I could try to extract the cleaned version of the pathway from that source, but my suspicion is that because the BioPAX processor does not (yet) handle biopax [`FragmentFeatures`](http://www.biopax.org/owldoc/Level3/classes/FragmentFeature___-1007651825.html) then it won't be able to parse the Pathway-commons version, either.

**Comment by bgyori** [comment]
Thanks, that's really useful context! INDRA now properly supports protein fragments and their grounding so in principle it should be possible to represent the whole cascade.

**Comment by bgyori** [comment]
I pushed a branch called `biopax_reactome` which implements the extraction of these reactions as INDRA Statements. To get the statements, try:
```python
from indra.sources import biopax
bp = biopax.process_owl('reactome.coagulation-cascade.biopax.xml')
bp.get_protein_conversions()
print(bp.statements)
```
The issue with this set of reactions turned out not to have to do with the BioPAX format or fragment features. Rather, the issue is that these reactions don't fit a high-level pattern with clear semantics, and so they can only be interpreted as generic "conversions" with some set of entities on the left hand side and some other entities on the right hand side of a biochemical reaction. I implemented a new extraction function called `get_protein_conversions` to extract these, this has to be called explicitly on the processor, as shown above. I also implemented a new feature to handle FragmentFeatures. The approach is to extract the begin and end sequence positions for the FragmentFeature, and then check our UniProt resources for a protein chain/fragment that matches those positions. We can then set the corresponding UniProt fragment grounding in db_refs['UPPRO'] as usual for protein fragments, and re-normalize the agent's name to the UniProt fragment name. I hope this is useful!

**Comment by djinnome** [comment]
Hi @bgyori 

Thanks so much, this is super useful!  I was speaking with our MD-PhD student, and he said these kinds of protein fragmentation processes happen all the time (for example, the renin-angiotensin system contains all sorts of protein fragments like Ang-I, Ang-II, converting each other etc) and are difficult to handle correctly from a modeling perspective for exactly the reasons you mention above.

**Comment by bgyori** [comment]
Thanks! I absolutely agree that these protein fragmentation cascades are important, and in fact the "clean" diagram you posted above is nice and template-like, fitting well with the template-like assertions that INDRA Statements represent. It's just that the way these reactions are implemented/modeled in this Reactome pathway, reactions often have sets of reactants and products between which the transformation doesn't fit a clean template. In any case, I'll finish up this branch and merge it soon.
