### ISSUE TITLE
TRIPS/DRUM parser options for full-text articles

### ISSUE THREAD

**Issue by sanyabt** [sorgerlab/indra#1318]
Hi @bgyori, I have been successfully using a local installation of REACH with INDRA for a few months now and would really like to be able to use the TRIPS reader for full text articles as well. Looking at the documentation and some of the existing issues, it seems like the API is not meant to handle large pieces of text. I looked at installing a local version of DRUM (https://github.com/wdebeaum/drum) on my system - however there are a lot of dependencies, some of them with deprecated links. 

I wanted to know if there are any alternate options to work with the TRIPS/DRUM reader with INDRA for processing large texts. Secondly, if using the API as in the documentation, what are the limits on number of words/paragraphs that can be processed? Will appreciate any help, thanks!

**Comment by bgyori** [comment]
Hi @sanyabt, thanks for your interest! Setting up TRIPS/DRUM for local reading is possible but not easy, especially natively on your machine, and indeed the instructions provided there have outdated links to certain resources. A more convenient approach is to use a Docker build, and I made a Dockerfile that does this but haven't pushed it to Github due to some non-public links/values. Once a Docker image is set up, TRIPS/DRUM can be used to read abstracts or full texts (supports NXML natively). However, it is a relatively slow system with abstracts taking up to a couple of minutes, and full texts 30+ minutes to read. If you're interested in the Docker option, please email me at ben.gyori@gmail.com and I can send instructions.
