### ISSUE TITLE
Handling duplicate statements in the various processors, or in the PySB assembler

### ISSUE THREAD

**Issue by johnbachman** [sorgerlab/indra#20]
Queries of BEL or BioPax can (and do) result in multiple equivalent statements, as in the following. They should be handled in some way, either by incrementing the count, or perhaps adding to a list of papers/references/contexts or other information that may differ between the different instances.

bp = biopax_api.process_pc_neighborhood(['BRAF'])
bp.get_phosphorylation()
...
Phosphorylation(NRAS, RAF1, PhosphorylationThreonine, 268)
Phosphorylation(NRAS, RAF1, PhosphorylationThreonine, 268)

**Comment by bgyori** [comment]
We don't check for duplicate statements but we do handle duplicate rules (that would result from duplicate statements) by displaying a warning in the assembler. I think this might be fine for now, especially since it is possible that different processors will collect 2 equivalent statements and pass it to the assembler.

**Comment by johnbachman** [comment]
Closed by the implementation of the Preassembler class as of, say, commit c48aff492a.
