### ISSUE TITLE
SMBL input and output

### ISSUE THREAD

**Issue by cthoyt** [sorgerlab/indra#206]
INDRA already has assemblers for BEL and BioPax. Can it integrate models coded in SMBL as well? 

I've found the documentation for exporting a PySB model to SMBL [here](http://docs.pysb.org/en/latest/modules/export/sbml.html) but it would be nice for there to be a convenience/wrapper function for outputting to SMBL in the INDRA interface. Perhaps you could include an example in your documentation's [basic usage examples](http://indra.readthedocs.io/en/latest/getting_started.html#basic-usage-examples)?

I think @dexterpratt would also be interested in this.

**Comment by bgyori** [comment]
Exporting PySB-assembled models to SBML can be done as follows
```
pa = PysbAssembler()
...
pa.make_model()
sbml_string = pa.export_model('sbml')
```
You can also pass an optional `file_name='my_model.sbml`' argument to `export_model` to save it into a file. I'll add this to the basic usage examples.

To clarify on your comment: INDRA can _read_ BEL and BioPAX and _produce_ SBML. Currently there is not BEL/BioPAX _output_ option or SBML _input_ option. Is there a use case in which these would be useful?

**Comment by johnbachman** [comment]
Following on Ben's point, though INDRA can't currently import from SBML, PySB can. See docs for pysb.importers: http://pysb.readthedocs.io/en/latest/modules/importers/index.html.

With respect to BEL output--I have an unpushed branch in which we use pybel (we are fans!) to create valid BEL script from INDRA Statements. I have some questions about that that I will take to another forum.

**Comment by cthoyt** [comment]
I'm sorry if these questions seem obvious, but I've spent a lot of time with BEL developing PyBEL and am now just beginning to get requests from users that want to integrate knowledge from BEL documents with their current knowledge bases stored in SMBL. 

I'm also unknowledgeable about the format of SMBL, and am not really sure about the limitations when comparing/contrasting BEL/SMBL/BioPax.

Again, my use case would be that I have a SMBL file and a BEL file, and I would like to add all of the information from BEL to make a combine SMBL file.

Thanks John for the tip - it would be wonderful if you could provide a code snippet for me as well :)

**Comment by johnbachman** [comment]
Interesting--my take: combining BEL and SBML is tricky in principle because BEL Statements (like INDRA Statements) are at the knowledge level whereas SBML models can include arbitrary biochemical reactions, including detailed implementations of high-level biochemical processes.

Generating biochemical reactions from BEL is doable (it's basically what INDRA's PysbAssembler does) but this will not guarantee consistency with the existing species and reactions in the SBML model. However, it could be possible if the SBML is sufficiently well-annotated (each species is grounded to database IDs, etc.) and the BEL->SBML conversion could take into account what is in the SBML model and try to assemble BEL into SBML in a consistent way.

Going the other direction, one could read the SBML reactions to "reverse engineer" the contents of the model back to the knowledge level, which could then be combined with BEL and then compiled *back* to SBML. However, this is also tricky because there are many ways a high-level statement could be compiled to SBML.

We haven't yet tried to "read" from models (i.e., SBML, Kappa, BNGL, etc.) for these reasons, however it's something we've recently been discussing as well. I would imagine the odds of success are better for SBML metabolism models (e.g., combining RECON with a BEL corpus) than for SBML-based signaling models.

**Comment by dexterpratt** [comment]
Hi John,

Using Charlie’s pybel.to_cx_json method (in the latest pybel) we could also go direct to CX / NDEx.

We’ve decided to move to the pybel encoding of bel in CX as our default bel format (though the existing BEL encoding will still be valid CX)

It has the advantage that it survives the round-trip through systems that support only node & edge attributes.

Dexter
