### ISSUE TITLE
TypeError in bng.py

### ISSUE THREAD

**Issue by FFroehlich** [sorgerlab/indra#235]
I am trying to run the following script:

```
import indra
from indra import bel
from indra.assemblers import PysbAssembler
from indra.assemblers import GraphAssembler

pa = PysbAssembler()
ga = GraphAssembler()

bp = bel.process_ndex_neighborhood(['BRAF', 'RAF1'])

pa.add_statements(bp.statements)
ga.add_statements(bp.statements)

modelpa = pa.make_model()
modelga = ga.make_model()

ga.save_pdf(file_name='graph_indra.pdf')
pa.export_model('sbml', file_name='indra.sbml')
```

The execution takes surprisingly long (>6h on my 2012 MBP) and then results in the following error:
>Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pysb/bng.py", line 384, in execute
    "\n" +
TypeError: a bytes-like object is required, not 'str'

>During handling of the above exception, another exception occurred:

>Traceback (most recent call last):
  File "./testINDRA.py", line 20, in <module>
    pa.export_model('sbml', file_name='indra.sbml')
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/indra/assemblers/pysb_assembler.py", line 906, in export_model
    exp_str = pysb.export.export(self.model, format)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pysb/export/__init__.py", line 153, in export
    return e.export()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pysb/export/sbml.py", line 103, in export
    pysb.bng.generate_equations(self.model)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pysb/bng.py", line 524, in generate_equations
    lines = iter(generate_network(model,cleanup=cleanup,verbose=verbose).split('\n'))
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pysb/bng.py", line 499, in generate_network
    bngfile.execute()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pysb/bng.py", line 387, in execute
    raise BngInterfaceError(e)
pysb.bng.BngInterfaceError: a bytes-like object is required, not 'str'

This looks like some incompatibility with BioNetGen, but I downloaded the binaries of the latest version (2.3.0).

**Comment by bgyori** [comment]
Hi, let me answer below, however this is a PySB/BNG issue so please post it as a PySB-to-BNG conversion issue (since the `pysb.bng.generate_equations(self.model)` line errors in PySB) to the PySB issues page: https://github.com/pysb/pysb/issues and I will close it here. 

The reasons, I think, you are getting an error: 
- PySB currently supports BNG version 2.2.6, not 2.3.0 yet. Please get version 2.2.6 from http://bionetgen.org/index.php/BioNetGen_Distributions. 
- Possibly a bug in PySB's BNG interface

The reason it's so slow:
- What happens is that INDRA makes a PySB model (in the `modelpa = pa.make_model()` line), probably fairly quickly. But when you call `pa.export_model('sbml')`, the PySB model needs to be converted into SBML. To do this, a rule-based model description needs to be generated out into a reaction network. PySB relies on BNG to do this generation. Since models are often combinatorially complex in a reaction network form, this model generation can take very long. Further, once the reaction network is generated by BNG, PySB needs to read it back in to then print it out in SBML form. There has been an open pull request to PySB for a month or so that improves on the speed of this: https://github.com/pysb/pysb/pull/276 but it hasn't been merged yet. Again, please post this problem to the PySB github.

**Comment by bgyori** [comment]
Hi @FFroehlich, could you post some details about how you installed

**Comment by FFroehlich** [comment]
Hi, thanks for the quick answer, I now installed BNG 2.2.6 and will try again.

I was expecting a model of managable size as the graph has ~30 nodes and roughly the same number of nodes. I will have a look at the final SBML file and if I still have the feeling that the computation time is too long I will open an issue in the PySB repository.

I cloned INDRA and then installed via `pip install .` . As far as I can remember I installed PySB via `pip install PySB`.

**Comment by bgyori** [comment]
Unfortunately, the number of molecule types and interactions aren't necessarily indicative of the complexity of the _reaction network_. One extreme example is a monomer which polymerizes: it's a single type of molecule and a single interaction but it produces an infinite number of individual molecular species and reactions. Another example, which is the one that I think you are running into here is the following: assume BEL gives you these interactions expressed as INDRA Statements:
```
Complex(A, B)
Complex(A, C)
Complex(B, C)
```
This will assemble into a PySB model that can be exported into Kappa and simulated using KaSim or exported into BNG and simulated using NFSim. However, since it produces an infinite reaction network (Consider that these set of interactions allow for the existence of arbitrarily large chains like A-B-C-A-B-C-...), it cannot be generated into one, and hence SBML export and ODE simulation will not be possible. 

This is one of the reasons why interactions taken directly from databases like the BEL Large Corpus cannot be used to make certain types of dynamical models. You can still
- Get the Statements from the BEL processor and examine them directly
- Assemble the Statements into various graphical formats or networks
- Assemble the Statements into PySB and analyze the rule-based model using agent-based simulation methods or static analysis

I am working on some new assembly policies in INDRA's PysbAssembler which would improve the assembly of multi-way Complex Statements like ```Complex(A,B,C)``` coming out of BEL more sensibly. But the example I gave above (with the three 2-way Complexes) will still cause problems.

**Comment by FFroehlich** [comment]
Okay, that makes sense. Thank you for the detailed explanation! 

Unfortunately installing BNG 2.2.6 did not fix the problem, consequently I opend an issue in the PySB repository.
