### ISSUE TITLE
PMC Client Error - cannotDisseminateFormat

### ISSUE THREAD

**Issue by cthoyt** [sorgerlab/indra#304]
There are quite a few PMC identifiers for which I'm getting this warning:

```
INFO: indra/rasmachine - Processing 17908174 for search term enumerated
WARNING: indra/pmc - PMC client returned with error cannotDisseminateFormat: The metadata format 'pmc' is not supported by the item or by the repository.
INFO: indra/rasmachine - 1 statements from PMID17908174 (abstract)
```

It looks like INDRA is still able to look up the abstract, but there's an issue with the preceding full-text lookup. Is it possible that the string `pmc` is just a mismatch?

**Comment by bgyori** [comment]
This happens when a PMC ID is available, suggesting that PMC could have NXML content for the paper. But when querying for this 'pmc' format (which is how one accesses NXML) the service comes back with this cannotDisseminateFormat error. The rasmachine recognizes that there's no PMC content and tries a PubMed abstract next.

**Comment by cthoyt** [comment]
Seems like this is not an issue then. Thanks for the support
