### ISSUE TITLE
Current bottlenecks in Indra

### ISSUE THREAD

**Issue by arey0pushpa** [sorgerlab/indra#306]
After reading and using indra it's clear what it can do but it's little unclear what it can't. A few resources and papers attached as links to this repository will help. I have a few specific questions :  
1. Is evry fact after parsed as indra statement is mechanisable ?
2. Is there any guarantee or notion of correctness present ?
   Is there any example (database of statements) where you show that the statements extracted do not 
   require manual check and all can be mechanisable. 
3. Ambiguity come due to imprecision of the natural language, any efforts in that direction?
Thanks for this beautiful tool.

**Comment by johnbachman** [comment]
Hi, thanks for your interest! I'll do my best to answer your questions.

> 1. Is evry fact after parsed as indra statement is mechanisable ?

INDRA's repertoire of Statements is in general mechanistic and can be mapped to sets of chemical reactions in a number of ways. The possible exceptions to this are the `RegulateActivity` Statements, `Activation` and `Inhibition`, which don't represent specific biochemical mechanisms but rather observed causal relationships. Nevertheless the `PysbAssembler` class, which is responsible for turning Statements into reactions, creates chemical reactions for these Statements as well, currently using the pseudo-first-order "one-step" policy. So in this sense, yes, every Statement that results from processing text is mechanisable.

> 2. Is there any guarantee or notion of correctness present ?
> Is there any example (database of statements) where you show that the statements
> extracted do not require manual check and all can be mechanisable.

This is a more difficult question to answer because it depends on what is meant by "correctness". INDRA will "correctly" execute a specified series of transformations on the modeling input, but it is sensitive to the content (mechanism description) that is provided, and can lead to unexpected or problematic results. In the natural language modeling use case, the modeler provides the mechanism description and is responsible for the content of the model and hence its causal integrity. If the modeler states that `RAF1 activates MAP2K1. MAP2K1 activates MAPK1.` these statements are certainly "mechanisable," but the modeler might be surprised to find that in the resulting model MAPK1 ends up activated even if RAF1 is not present. This is because the modeler did not specify that `Active MAP2K1 activates MAPK1.` This is a very simple example; though not described in our Biorxiv preprint, INDRA can also be used to process mechanisms from the scientific literature, a use case involving millions of (often noisy and error prone) extractions, which leads to many more difficult and challenging *assembly* issues. See e.g., the modules in https://github.com/sorgerlab/indra/tree/master/indra/preassembler, https://github.com/sorgerlab/indra/blob/master/indra/belief/__init__.py, and https://github.com/sorgerlab/indra/blob/master/indra/mechlinker/__init__.py. These modules deal with the biggest issues we have encountered in getting "good" models out of databases and literature--so far. Finding ways to constrain and check models produced by INDRA for certain desired properties is an active area that we are pursuing ourselves and with collaborators. Given your interests you should also check out the Syndra project at https://github.com/csvoss/syndra.

> 3. Ambiguity come due to imprecision of the natural language, any efforts in that direction?
> Thanks for this beautiful tool.

With regard to ambiguity, currently the system takes what is given in the natural language input, along with any ambiguity, and carries that ambiguity forward into the resulting model. This can lead to models that are combinatorially complex in terms of the number of possible chemical species and reactions. For example, if I assert that `A binds B. B binds C. C binds A`, I might be thinking of the assembly of the heterotrimer A-B-C, but what I will get in addition are infinite polymers of the form A-B-C-A-B-C-A... Constraining the set of species that are formed requires making additional assertions, which can be provided in the form of natural language. As this relates to the use of INDRA to render colloquial word models in biology in executable form, we tend to think of this more as a feature than as a bug, because it highlights the ambiguities that are *inherent* in the way people talk about biological mechanisms, and allows for the opportunity to provide clarity at the language level rather than a modeler baking these assumptions directly into the mathematical representation.

One other thing to note on the subject of ambiguity is that in our work in the [Communicating with Computers](https://www.darpa.mil/program/communicating-with-computers) project, we are embedding INDRA within an interactive dialog system, which gives the machine the opportunity to identify different types of ambiguity and ask for clarification when required.

**Comment by arey0pushpa** [comment]
Thank you so much, Trying to understand completely and possibly contribute.  Have you collected a database? Is it available her on the repository (not sure whether \data contains it)? I would love to see it and play with for some time to understand what to do? how to do it? and specially how to workaround to create GOOD models. Cheers for your detailed answer.
