### ISSUE TITLE
Mutations represented as Agent condition

### ISSUE THREAD

**Issue by bgyori** [sorgerlab/indra#49]
I started implementing MutConditions - a named tuple to represent amino acid substitutions on INDRA Agents. I suggest the following format:
MutCondition = namedtuple('MutCondition', ['pos', 'residue_from', 'residue_to'])

There are several important questions that we need to consider. For instance:

1. Is it enough to represent mutations that involve a single amino acid change? Or is a more general representation worth the effort?

2. Should we allow more than one MutCondition on an Agent?

3. What is the assumption if mutation is not given? Should we assume that it refers to WT or should it be interpreted as applying to both WT and all mutated forms?

4. How to handle refinements (in preassembler)? Is a mutated form a refinement of an agent with unspecified mutation status?

5. If a statement refers explicitly to WT, how do we represent it?

**Comment by johnbachman** [comment]
1. We should probably also allow representation of deletions, since these can be important--I'm thinking in particular of the Exon 19 deletions in EGFR which are frequently associated with lung cancer (see https://www.mycancergenome.org/content/disease/lung-cancer/egfr/21/) 

2. We should allow more than one MutCondition on an agent in part because such mutations are common in biochemical studies to identify function.

3. If no mutation is given, I think it's fair to consider it as applying to both WT and mutated forms until more specific information about the behavior of the mutant is provided.

4. My initial response is that, for a given mutant, information about mutants represents a refinement over information from WT. That is, the information that Ras G12D lacks GTP-ase activity would be a refinement over the information the WT Ras has GTPase activity. But that doesn't mean that we discard the statement about WT.

5. We could either represent the mutation as being the original amino acid (e.g., Ras G12=G) or as being wild type (e.g. Ras G12='WT') or perhaps no mutation at that position (e.g Ras G12=None).

**Comment by jmuhlich** [comment]
I think "mutation not specified" and "explicitly WT" are the same thing. WT is sort of the "default" when more specific information about sequence isn't given. Of course this includes some variance around SNPs and other natural variations, so WT isn't really one concrete sequence. I have thought a lot about this as part of my work on the Protein Line Notation.

Do we need `residue_from`? Isn't that implied by the sequence? In writing, it's included for redundancy I think, but if we've already verified that the parsed equivalent of `residue_from` matches the sequence then I'm not convinced that we need to track it ourselves.

**Comment by bgyori** [comment]
I think residue_from is useful because then we will be able to make intuitive site names without having to correctly ground and look up the sequence of a protein. For instance we would not be able to assemble KRAS(G12='V') without the reference sequence.

**Comment by bgyori** [comment]
In the interest of time I implemented a simple version of this as of: 6f317c64e24b766bbafceb4663f45434f37fd981
