### ISSUE TITLE
Sparser content in database is missing PMIDs or contains PMCIDs instead

### ISSUE THREAD

**Issue by johnbachman** [sorgerlab/indra#545]
In poking around the database content, I found that statements extracted by Sparser all were missing pmids in their evidence fields. Some examples:

```[Evidence(sparser, None, {}, These results suggest H63D HFE increases tau phosphorylation via GSK-3β activity and iron-mediated oxidative stress.),
 Evidence(sparser, None, {}, On the other hand, a single-dose intraventricular injection of an Aβ antibody in 4-month-old mice cleared intraneuronal Aβ pathology and reduced early cognitive deficits [ xref ], and inhibition of GSK-3β attenuated Aβ-induced tau phosphorylation in vitro and can reduce tau pathology in vivo [ xref , xref ].),
 Evidence(sparser, None, {}, Hence, although tau hyperphosphorylation induced by protein phosphatase inhibition contributes to pathological aggregate formation, only hyperphosporylation of tau followed by proteasome inhibition leads to stable fibrillary deposits of tau similar to those observed in neurodegenerative diseases.),
 Evidence(sparser, None, {}, Tau phosphorylation induced by arsenite did not involve glycogen synthase kinase-3 or protein phosphatase-1 or -2, but the activity responsible for tau hyperphosphorylation could be inhibited with the protein kinase inhibitor roscovitine.),
 Evidence(sparser, None, {}, The phosphorylation of tau was increased by treating the cells with forskolin and rolipram, which elevate cyclic AMP levels, by treating with the phosphatase inhibitor okadaic acid, or by treating with a combination of both treatments.)]
```
In other cases, there were actually PMC ids in the evidence.pmid field. Some examples:

```
Evidence(sparser, PMC7265456, {}, We found that in PC12 cells treated with NGF or fibroblast growth factor-2, glycogen synthase kinase-3beta and tau were upregulated simultaneously from around day 2 of differentiation, with increasing glycogen synthase kinase-3-mediated tau phosphorylation.),
 Evidence(sparser, PMC7265724, {}, Phosphorylated tau and alpha-synuclein frequently colocalized.),
 Evidence(sparser, PMC7265724, {}, This observation suggests that the defect in intracellular cholesterol trafficking in NPC1 may provoke aberrant phosphorylation of alpha-synuclein and tau, and that this phosphorylation is enhanced by the ApoE epsilon4 allele.),
 Evidence(sparser, PMC7266763, {}, However, the abnormal phosphorylation of tau is also a reasonable target and as the molecular basis of AD is better delineated, more targeted treatment approaches are being proposed.),
 Evidence(sparser, PMC7268140, {}, Significantly, ABalphaC, a major protein phosphatase 2A (PP2A) holoenzyme, specifically binds to and dephosphorylates tau.),
 Evidence(sparser, PMC7268140, {}, Deregulation of PP2A results in tau hyperphosphorylation in vivo.),
```

**Comment by pagreene** [comment]
Back in February we decided to ("for the time being") simply set the pmid slot of statements to None, due to challenges tracking provenance through reading, and with the idea that we would eventually update the evidence id's section to be more general.  In fact REACH statements should I think have None for pmids as well.

I think the idea might also have been that, if retrieved from the database, the pmid can be easily traced with database queries.

Also, those aren't actual PMC ids. They are the names of files used to get Sparser to read them (sparser requires a prefix of 'PMC'), but the numbers are actually text content ids, I believe. This was the older system of filling that void, which was superseded by the above mentioned None-filling.

We can definitely find a way to solve this issue. I think the key issue is that the reading system is designed to not care if content comes from the database, which is why it is hard to track through reading. However, we could implement something in the database reading wrapper which after-the-fact adds pmids to the evidence.

Alternatively, we could insert the pmid on-load when we get statements. Now that I've indexed the path from text refs to statements, it's fast to do this join, so this might actually be the most practical solution. The only downside is that you would only get the pmids if you got the statements using the client functions, but I think we're kind of gravitating towards that paradigm (of not-totally-general-but-good-enough wrappers that can be used in most cases) anyways.

**Comment by pagreene** [comment]
This was resolved a while ago by #627

**Comment by cthoyt** [comment]
@pagreene is there any way to recover the PMIDs from INDRA UUID's? We have a lot of content we curated but don't have original provenance :/

**Comment by pagreene** [comment]
In principle yes. In practice, it might take some work. It would be easier to use the matches-key hashes, which is already supported by the REST API.

**Comment by cthoyt** [comment]
Okay, so I have pickles of the original lists of statements so I think I can derive a mapping from UUID to matches-key hashes (assuming that when I did this, the Statement class had the most recent version of the matches-key hashing algorithm built-in). Would I be able to reconstitute matches-key hashes myself, or would you need to help me with some direct database magic?

Here's an example curation sheet we were using (sorry for excel instead of TSV - GitHub would only allow this format embedded): [CTTN.bel.xlsx](https://github.com/sorgerlab/indra/files/2390074/CTTN.bel.xlsx)
