### ISSUE TITLE
Error in get_version

### ISSUE THREAD

**Issue by cthoyt** [sorgerlab/indra#703]
```python
import indra
print(indra.util.get_version.get_version())
```

results in the following error after doing `pip install indra`

```python-traceback
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-6-78b55e5a3891> in <module>()
----> 1 print(indra.util.get_version.get_version())

~/.virtualenvs/hbp/lib/python3.7/site-packages/indra/util/get_version.py in get_version(with_git_hash, refresh_hash)
     50                 except CalledProcessError:
     51                     ret = 'UNHASHED'
---> 52             INDRA_GITHASH = ret.strip().decode('utf-8')
     53         version = '%s-%s' % (version, INDRA_GITHASH)
     54     return version

AttributeError: 'str' object has no attribute 'decode'
```

**Comment by bgyori** [comment]
Setting aside the specific error, the underlying issue is that `get_version` is specifically aimed at creating a version string based on the state of a local git repository. If indra is pip installed, there is no git metadata and so calling this function with default parameters would error in an obscure way like this. Depending on what you're trying to do, you could use
```
import indra
indra.__version__
```
to get the release version that `pip install indra` installed. What do you think?

**Comment by bgyori** [comment]
I'll close this now since it seems to work as expected as long as the repo is git cloned.

**Comment by cthoyt** [comment]
Sorry for going dark on this. Thanks for the hint from before :)
