### ISSUE TITLE
Any way to automatically assign rate constants?

### ISSUE THREAD

**Issue by jadeshi** [sorgerlab/indra#817]
This might be too ambitious of a question, but could there possibly be a way to automate assignment of rate constants to models as well? For example, could a future version of INDRA interface with existing databases like SABIO-RK (sabio.h-its.org/) or extract rate information through papers via NLP? I am aware that kinetic information like this is substantially more difficult to obtain experimentally, so maybe the overall data available is too sparse for this to be a worthwhile thing to consider at this point.

**Comment by bgyori** [comment]
Hi @jadeshi, that's a really good question! 

First, I recently extended the PySB assembler (indra.assemblers.pysb.PysbAssembler) to be able to take in parameter values supplied by the user upon assembly time. If parameters are not supplied, they are generated automatically based on plausible nominal values with respect to the role the rate constant plays in a given mechanism (e.g., binding/dissociation/catalysis/Km etc.). The assembler also has the ability to set the total amounts of proteins (corresponding to model initial conditions) automatically by pulling in expression profiles from CCLE.

In terms of automatically gathering rate constants, your ideas make sense and we've considered them. In my experience, SABIO-RK is stronger in the area of metabolism, where the role of rate constants in a given mechanism is more straightforward, and not so much in signaling, where due to combinatorial complexity, rate constants are difficult to uniquely associate with an interaction. It is also questionable whether rate constants published in the literature are applicable in a model that may be built for a different context (e.g., in an in-vitro vs cell-based setting or in one cell type vs another). Nevertheless, we are aware of some efforts to extract rate constants from text using NLP, (for instance https://github.com/sgarg87/big_mech_isi_gg). At the end of the day, the solution is typically to use time course data collected in context the model is supposed to be applied in and fit model parameters to the data for which there are many downstream methods and tools to connect with (e.g. by exporting the PySB model generated by INDRA as SBML).

**Comment by bgyori** [comment]
Hopefully my answer was adequate, I'll close this issue now.
